version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  web:
    build:
      context: .
      dockerfile: docker/local/web/Dockerfile
    image: easysport_django
    depends_on:
      - postgres
    volumes:
      - ./web/:/code
    env_file:
      - .envs/.local/.web
      - .envs/.local/.postgres
    ports:
      - "80:80"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: docker/production/postgres/Dockerfile
    image: easysport_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .envs/.local/.postgres